#ifndef FF_MOTIFS_FFI_H
#define FF_MOTIFS_FFI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ConfigHandle ConfigHandle;

typedef struct SimHandle SimHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct SimHandle *sim_create(const char *params,
                             double celsius,
                             double k0,
                             double k3ws,
                             double k4ws);

void sim_destroy(struct SimHandle *handle);

/**
 * Create a CotransConfig from the target structure.
 * dom_length_keys and dom_length_values are parallel arrays of length n_domains.
 * num_workers: 0 = Rayon default (all cores), 1 = serial (safe for OpenMP), N = N threads
 */
struct ConfigHandle *config_create(const char *acfp,
                                   const char *dl_seq,
                                   const char *const *dom_length_keys,
                                   const uintptr_t *dom_length_values,
                                   uintptr_t n_domains,
                                   double t_ext,
                                   double t_end,
                                   uintptr_t num_sims,
                                   double threshold,
                                   uintptr_t num_workers);

void config_destroy(struct ConfigHandle *handle);

uintptr_t config_nl_path_len(struct ConfigHandle *handle);

/**
 * Copies nl_path[index] into out_buf (caller-allocated, size >= buf_len).
 * Returns bytes written (excluding null terminator), or 0 on error.
 */
uintptr_t config_nl_path_entry(struct ConfigHandle *handle,
                               uintptr_t index,
                               char *out_buf,
                               uintptr_t buf_len);

/**
 * Full timecourse — no checkpoints, runs to t_end.
 * Writes per-timepoint total motif counts (excluding Unassigned) into flat arrays.
 * Returns number of timepoints written, or -1 on error.
 * out_nucleotides and out_counts must be pre-allocated with capacity >= max_timepoints.
 */
int sim_timecourse(struct SimHandle *sim_handle,
                   struct ConfigHandle *config_handle,
                   const char *sequence,
                   uintptr_t *out_nucleotides,
                   uintptr_t *out_counts,
                   uintptr_t max_timepoints);

/**
 * Checkpoint timecourse — early-exits if occupancy falls below threshold.
 * Same output format as sim_timecourse.
 * Returns number of timepoints written (may be less than total if checkpoint failed),
 * or -1 on error.
 */
int sim_timecourse_checkpoints(struct SimHandle *sim_handle,
                               struct ConfigHandle *config_handle,
                               const char *sequence,
                               uintptr_t *out_nucleotides,
                               uintptr_t *out_counts,
                               uintptr_t max_timepoints);

/**
 * Set per-checkpoint weights for a config.
 * weights must be a pointer to n_weights doubles, one per checkpoint segment (in order).
 * If fewer weights than checkpoints, remaining checkpoints use weight 1.0.
 * Pass null or n_weights=0 to reset to equal weights.
 */
void config_set_weights(struct ConfigHandle *handle, const double *weights, uintptr_t n_weights);

/**
 * Set the T-domain occupancy scoring mode for a config and rebuild check_positions.
 * "full" (default): average occupancy over every T-domain nucleotide position.
 * "endpoint":       score only at the last T-domain position per segment.
 *                   Use with flexible T-domains to reward keeping T short while
 *                   achieving high occupancy at the final transcribed position.
 */
void config_set_t_scoring(struct ConfigHandle *handle, const char *mode);

/**
 * Cap per-segment occupancy at this threshold before weighting (default 1.0 = no cap).
 * Values outside [0,1] are clamped. Use with endpoint mode to prevent
 * over-extending T domains for marginal occupancy gains.
 */
void config_set_t_occ_threshold(struct ConfigHandle *handle, double threshold);

/**
 * Penalty subtracted from effective occupancy per extra T-domain nucleotide
 * (actual_len - min_len). Default 0.0 (no penalty). Requires t_min_lengths to be set.
 */
void config_set_t_len_penalty(struct ConfigHandle *handle, double penalty);

/**
 * Set minimum lengths for T domains. Required for t_len_penalty to take effect.
 * keys[i] is the T-domain name (e.g. "T0"), vals[i] is its minimum length.
 */
void config_set_t_min_lengths(struct ConfigHandle *handle,
                              const char *const *keys,
                              const uintptr_t *vals,
                              uintptr_t n);

/**
 * Set the scoring objective for a config.
 * Valid values: "occupancy" (default) or "distance".
 */
void config_set_objective(struct ConfigHandle *handle, const char *objective);

/**
 * Scalar objective for gradient descent.
 * Dispatches to occupancy or distance scoring based on config.objective.
 * Returns score in [0, 1] (lower is better), or -1.0 on error.
 */
double sim_score(struct SimHandle *sim_handle,
                 struct ConfigHandle *config_handle,
                 const char *sequence);

/**
 * Objective + per-checkpoint scores for gradient descent with experience replay.
 *
 * Writes into out_scores[0..n+1]:
 *   out_scores[0]   = total weighted score (same as sim_score)
 *   out_scores[1..] = per-checkpoint normalized distances/scores, one per checkpoint
 *
 * Returns n+1 (total entries written), or -1 on error.
 * max_scores must be >= n_checkpoints + 1; values beyond n+1 are not written.
 */
int sim_score_vec(struct SimHandle *sim_handle,
                  struct ConfigHandle *config_handle,
                  const char *sequence,
                  double *out_scores,
                  uintptr_t max_scores);

/**
 * Batch scalar scoring — evaluates n_seqs sequences in parallel using Rayon.
 *
 * sequences: array of n_seqs C-string pointers (each a null-terminated RNA sequence).
 * out_scores: caller-allocated array of n_seqs doubles; receives the score for each
 *             sequence (same semantics as sim_score: [0,1] lower-is-better, -1.0 on error).
 *
 * Returns n_seqs on success, or -1 if either handle is null.
 * Individual sequences that fail to score write -1.0 into their out_scores slot.
 */
int sim_score_batch(struct SimHandle *sim_handle,
                    struct ConfigHandle *config_handle,
                    const char *const *sequences,
                    uintptr_t n_seqs,
                    double *out_scores);

/**
 * Compute both distance and occupancy scores from a single simulation pass.
 *
 * Uses distance-based early exit. Writes dist_score and occ_score to the
 * respective output pointers (each in [0, 1], lower is better).
 * Returns 0 on success, -1 on error.
 */
int sim_score_both(struct SimHandle *sim_handle,
                   struct ConfigHandle *config_handle,
                   const char *sequence,
                   double *out_dist,
                   double *out_occ);

/**
 * Like sim_score_both, but also fills per-segment breakdowns.
 *
 * out_dist:      aggregated distance score  (0=best, 1=worst).
 * out_occ:       aggregated occupancy score (0=best, 1=worst, inverted for consistency).
 * out_dist_segs: per-segment distance  [n_segs] (0=best, 1=worst).
 * out_occ_segs:  per-segment raw occ   [n_segs] (1=best, 0=worst — NOT inverted).
 * n_segs:        size of out_dist_segs / out_occ_segs; use config_nl_path_len().
 *
 * Null pointers for out_dist / out_occ / out_dist_segs / out_occ_segs are tolerated
 * (those outputs are simply skipped).  n_segs may be 0 to skip per-segment output.
 * Returns 0 on success, -1 on error.
 */
int sim_score_detailed(struct SimHandle *sim_handle,
                       struct ConfigHandle *config_handle,
                       const char *sequence,
                       double *out_dist,
                       double *out_occ,
                       double *out_dist_segs,
                       double *out_occ_segs,
                       uintptr_t n_segs);

/**
 * Batch combined scoring — evaluates n_seqs sequences in parallel using Rayon.
 *
 * sequences: array of n_seqs C-string pointers.
 * out_dist, out_occ: caller-allocated arrays of n_seqs doubles.
 * Each entry receives [0, 1] lower-is-better scores, or -1.0 on per-sequence error.
 * Returns n_seqs on success, -1 if handles are null.
 */
int sim_score_both_batch(struct SimHandle *sim_handle,
                         struct ConfigHandle *config_handle,
                         const char *const *sequences,
                         uintptr_t n_seqs,
                         double *out_dist,
                         double *out_occ);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FF_MOTIFS_FFI_H */
