#ifndef FF_MOTIFS_FFI_H
#define FF_MOTIFS_FFI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ConfigHandle ConfigHandle;

typedef struct SimHandle SimHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct SimHandle *sim_create(const char *params,
                             double celsius,
                             double k0,
                             double k3ws,
                             double k4ws);

void sim_destroy(struct SimHandle *handle);

/**
 * Create a CotransConfig from the target structure.
 * dom_length_keys and dom_length_values are parallel arrays of length n_domains.
 * num_workers: 0 = Rayon default (all cores), 1 = serial (safe for OpenMP), N = N threads
 */
struct ConfigHandle *config_create(const char *acfp,
                                   const char *dl_seq,
                                   const char *const *dom_length_keys,
                                   const uintptr_t *dom_length_values,
                                   uintptr_t n_domains,
                                   double t_ext,
                                   double t_end,
                                   uintptr_t num_sims,
                                   double threshold,
                                   uintptr_t num_workers);

void config_destroy(struct ConfigHandle *handle);

uintptr_t config_nl_path_len(struct ConfigHandle *handle);

/**
 * Copies nl_path[index] into out_buf (caller-allocated, size >= buf_len).
 * Returns bytes written (excluding null terminator), or 0 on error.
 */
uintptr_t config_nl_path_entry(struct ConfigHandle *handle,
                               uintptr_t index,
                               char *out_buf,
                               uintptr_t buf_len);

/**
 * Full timecourse — no checkpoints, runs to t_end.
 * Writes per-timepoint total motif counts (excluding Unassigned) into flat arrays.
 * Returns number of timepoints written, or -1 on error.
 * out_nucleotides and out_counts must be pre-allocated with capacity >= max_timepoints.
 */
int sim_timecourse(struct SimHandle *sim_handle,
                   struct ConfigHandle *config_handle,
                   const char *sequence,
                   uintptr_t *out_nucleotides,
                   uintptr_t *out_counts,
                   uintptr_t max_timepoints);

/**
 * Checkpoint timecourse — early-exits if occupancy falls below threshold.
 * Same output format as sim_timecourse.
 * Returns number of timepoints written (may be less than total if checkpoint failed),
 * or -1 on error.
 */
int sim_timecourse_checkpoints(struct SimHandle *sim_handle,
                               struct ConfigHandle *config_handle,
                               const char *sequence,
                               uintptr_t *out_nucleotides,
                               uintptr_t *out_counts,
                               uintptr_t max_timepoints);

/**
 * Scalar objective for gradient descent.
 * score = pathlength - sum(avg T-domain occupancies)
 * range: [0, pathlength], lower is better.
 * Returns -1.0 on error.
 */
double sim_score(struct SimHandle *sim_handle,
                 struct ConfigHandle *config_handle,
                 const char *sequence);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FF_MOTIFS_FFI_H */
